using ANcpLua.Sdk.Tests.Helpers;
using ANcpLua.Sdk.Tests.Infrastructure;

namespace ANcpLua.Sdk.Tests;

public class ClaudeBrainTests(PackageFixture fixture, ITestOutputHelper testOutputHelper)
{
    private readonly PackageFixture _fixture = fixture;
    private readonly ITestOutputHelper _testOutputHelper = testOutputHelper;

    [Fact]
    public async Task ClaudeBrain_Generates_File_When_Enabled()
    {
        await using var project =
            new ProjectBuilder(_fixture, _testOutputHelper, SdkImportStyle.SdkElement, PackageFixture.SdkName);

        // 1. Setup Root CLAUDE.md
        project.AddFile("CLAUDE.md", "This is the root brain.");

        // 2. Add Project in a subfolder (to test relative path resolution)
        project.AddCsprojFile(
            [
                (MsBuildProperties.TargetFramework, TargetFrameworks.Net100),
                (MsBuildProperties.OutputType, MsBuildValues.Library),
                ("GenerateClaudeMd", "true") // Must explicitly enable
            ],
            filename: "src/MyLibrary/MyLibrary.csproj");

        // 3. Build
        var result = await project.BuildAndGetOutput(["src/MyLibrary/MyLibrary.csproj"]);

        Assert.Equal(0, result.ExitCode);

        // 4. Verify Generation
        var generatedFilePath = project.RootFolder / "src/MyLibrary/CLAUDE.md";
        Assert.True(File.Exists(generatedFilePath), "CLAUDE.md should have been generated.");

        var content = await File.ReadAllTextAsync(generatedFilePath, TestContext.Current.CancellationToken);

        // Check content parts - the SDK generates a markdown link format
        Assert.Contains("See [Root CLAUDE.md]", content); // Link to root
        Assert.Contains("# MyLibrary", content); // Project Name
    }

    [Fact]
    public async Task ClaudeBrain_Does_Not_Generate_By_Default()
    {
        await using var project =
            new ProjectBuilder(_fixture, _testOutputHelper, SdkImportStyle.SdkElement, PackageFixture.SdkName);

        project.AddFile("CLAUDE.md", "Root brain");

        project.AddCsprojFile(
            [
                (MsBuildProperties.TargetFramework, TargetFrameworks.Net100)
                // Default is false
            ],
            filename: "src/MyLibrary/MyLibrary.csproj");

        await project.BuildAndGetOutput(["src/MyLibrary/MyLibrary.csproj"]);

        var generatedFilePath = project.RootFolder / "src/MyLibrary/CLAUDE.md";
        Assert.False(File.Exists(generatedFilePath), "CLAUDE.md should NOT have been generated by default.");
    }

    [Fact]
    public async Task ClaudeBrain_Does_Not_Overwrite_Existing()
    {
        await using var project =
            new ProjectBuilder(_fixture, _testOutputHelper, SdkImportStyle.SdkElement, PackageFixture.SdkName);

        project.AddFile("CLAUDE.md", "Root brain");

        // Pre-create the file
        project.AddFile("src/MyLibrary/CLAUDE.md", "Existing content");

        project.AddCsprojFile(
            [
                (MsBuildProperties.TargetFramework, TargetFrameworks.Net100)
            ],
            filename: "src/MyLibrary/MyLibrary.csproj");

        await project.BuildAndGetOutput(["src/MyLibrary/MyLibrary.csproj"]);

        var generatedFilePath = project.RootFolder / "src/MyLibrary/CLAUDE.md";
        var content = await File.ReadAllTextAsync(generatedFilePath, TestContext.Current.CancellationToken);

        Assert.Equal("Existing content", content);
    }
}
