namespace ANcpLua.Sdk.Tests;

public class ClaudeBrainTests(PackageFixture fixture)
{
    private readonly PackageFixture _fixture = fixture;

    [Fact]
    public async Task ClaudeBrain_Generates_File_By_Default()
    {
        await using var project = SdkProjectBuilder.Create(_fixture);

        project.AddFile("CLAUDE.md", "This is the root brain.");

        var result = await project
            .WithFilename("src/MyLibrary/MyLibrary.csproj")
            .BuildAsync(["src/MyLibrary/MyLibrary.csproj"]);

        Assert.Equal(0, result.ExitCode);

        var generatedFilePath = project.RootFolder / "src/MyLibrary/CLAUDE.md";
        Assert.True(File.Exists(generatedFilePath), "CLAUDE.md should have been generated by default.");

        var content = await File.ReadAllTextAsync(generatedFilePath, TestContext.Current.CancellationToken);

        Assert.Contains("See [Root CLAUDE.md]", content);
        Assert.Contains("# MyLibrary", content);
    }

    [Fact]
    public async Task ClaudeBrain_Does_Not_Generate_When_Disabled()
    {
        await using var project = SdkProjectBuilder.Create(_fixture);

        project.AddFile("CLAUDE.md", "Root brain");

        await project
            .WithFilename("src/MyLibrary/MyLibrary.csproj")
            .WithProperty("GenerateClaudeMd", Val.False)
            .BuildAsync(["src/MyLibrary/MyLibrary.csproj"]);

        var generatedFilePath = project.RootFolder / "src/MyLibrary/CLAUDE.md";
        Assert.False(File.Exists(generatedFilePath), "CLAUDE.md should NOT have been generated when disabled.");
    }

    [Fact]
    public async Task ClaudeBrain_Does_Not_Overwrite_Existing()
    {
        await using var project = SdkProjectBuilder.Create(_fixture);

        project.AddFile("CLAUDE.md", "Root brain");
        project.AddFile("src/MyLibrary/CLAUDE.md", "Existing content");

        await project
            .WithFilename("src/MyLibrary/MyLibrary.csproj")
            .BuildAsync(["src/MyLibrary/MyLibrary.csproj"]);

        var generatedFilePath = project.RootFolder / "src/MyLibrary/CLAUDE.md";
        var content = await File.ReadAllTextAsync(generatedFilePath, TestContext.Current.CancellationToken);

        Assert.Equal("Existing content", content);
    }
}
