// Copyright (c) ANcpLua. All rights reserved.
// Licensed under the MIT License.

#if ANCPLUA_SOURCEGEN_HELPERS
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace ANcpLua.SourceGen;

/// <summary>
/// Extension methods for <see cref="SourceProductionContext"/>.
/// </summary>
internal static class SourceProductionContextExtensions
{
    /// <summary>
    /// Adds source code with a standardized header.
    /// </summary>
    public static void AddSourceWithHeader(
        this SourceProductionContext context,
        string hintName,
        string sourceCode,
        string? generatorName = null)
    {
        var header = GenerateHeader(generatorName ?? "ANcpLua.SourceGen");
        var fullSource = header + sourceCode;
        context.AddSource(hintName, SourceText.From(fullSource, Encoding.UTF8));
    }

    /// <summary>
    /// Adds source code from a StringBuilder with a standardized header.
    /// </summary>
    public static void AddSourceWithHeader(
        this SourceProductionContext context,
        string hintName,
        StringBuilder sourceBuilder,
        string? generatorName = null)
    {
        AddSourceWithHeader(context, hintName, sourceBuilder.ToString(), generatorName);
    }

    /// <summary>
    /// Reports a diagnostic from a <see cref="DiagnosticInfo"/>.
    /// </summary>
    public static void ReportDiagnostic(this SourceProductionContext context, DiagnosticInfo diagnosticInfo)
    {
        context.ReportDiagnostic(diagnosticInfo.ToDiagnostic());
    }

    private static string GenerateHeader(string generatorName)
    {
        return $"""
            // <auto-generated/>
            // Generated by {generatorName}
            #nullable enable

            """;
    }
}

#endif