// <auto-generated />
#nullable enable

namespace ANcpLua.Analyzers;

/// <summary>
/// Base class for diagnostic analyzers that standardizes initialization.
/// Automatically configures:
/// - GeneratedCodeAnalysisFlags.None (don't analyze generated code)
/// - EnableConcurrentExecution() for performance
/// </summary>
public abstract class DiagnosticAnalyzerBase : Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer
{
    public sealed override void Initialize(Microsoft.CodeAnalysis.Diagnostics.AnalysisContext context)
    {
        context.ConfigureGeneratedCodeAnalysis(Microsoft.CodeAnalysis.Diagnostics.GeneratedCodeAnalysisFlags.None);
        context.EnableConcurrentExecution();
        InitializeCore(context);
    }

    /// <summary>
    /// Register analysis actions. Called after standard configuration.
    /// </summary>
    protected abstract void InitializeCore(Microsoft.CodeAnalysis.Diagnostics.AnalysisContext context);
}
