using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ANcpLua.AspNetCore.ServiceDefaults.AutoRegister;

[Generator]
public sealed class ServiceDefaultsAutoRegisterGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var locations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is InvocationExpressionSyntax
                {
                    ArgumentList.Arguments.Count: 0,
                    Expression: MemberAccessExpressionSyntax
                    {
                        Name.Identifier.ValueText: "Build"
                    }
                },
                transform: static (ctx, _) => GetInterceptLocation(ctx))
            .Where(static x => x is not null)
            .Select(static (x, _) => x!.Value)
            .Collect();

        context.RegisterSourceOutput(locations, static (spc, items) =>
        {
            if (items.IsDefaultOrEmpty)
                return;

            Emit(spc, items.Distinct().ToImmutableArray());
        });
    }

    private static InterceptLocation? GetInterceptLocation(GeneratorSyntaxContext context)
    {
        var invocation = (InvocationExpressionSyntax)context.Node;
        if (invocation.Expression is not MemberAccessExpressionSyntax memberAccess)
            return null;

        var symbol = context.SemanticModel.GetSymbolInfo(invocation).Symbol as IMethodSymbol;
        if (symbol is null)
            return null;

        if (!string.Equals(symbol.Name, "Build", StringComparison.Ordinal))
            return null;

        if (!string.Equals(symbol.ContainingType.Name, "WebApplicationBuilder", StringComparison.Ordinal))
            return null;

        if (!string.Equals(symbol.ContainingNamespace.ToDisplayString(), "Microsoft.AspNetCore.Builder", StringComparison.Ordinal))
            return null;

        var span = memberAccess.Name.Identifier.GetLocation().GetLineSpan();
        if (string.IsNullOrEmpty(span.Path))
            return null;

        return new InterceptLocation(span.Path, span.StartLinePosition.Line + 1, span.StartLinePosition.Character + 1);
    }

    private static void Emit(SourceProductionContext context, ImmutableArray<InterceptLocation> locations)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace System.Runtime.CompilerServices");
        sb.AppendLine("{");
        sb.AppendLine("    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]");
        sb.AppendLine("    internal sealed class InterceptsLocationAttribute : Attribute");
        sb.AppendLine("    {");
        sb.AppendLine("        public InterceptsLocationAttribute(string filePath, int line, int column) { }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("namespace ANcpLua.AspNetCore.ServiceDefaults.AutoRegister.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    internal static class WebApplicationBuilderInterceptors");
        sb.AppendLine("    {");

        for (var i = 0; i < locations.Length; i++)
        {
            var location = locations[i];
            var escapedPath = EscapeForCSharpString(location.FilePath);

            sb.AppendLine("        #pragma warning disable CS9270");
            sb.AppendLine($"        [System.Runtime.CompilerServices.InterceptsLocation(\"{escapedPath}\", {location.Line}, {location.Column})]");
            sb.AppendLine("        #pragma warning restore CS9270");
            sb.AppendLine($"        public static WebApplication Build_{i}(WebApplicationBuilder builder)");
            sb.AppendLine("        {");
            sb.AppendLine("            builder.Services.AddSingleton<global::ANcpLua.AspNetCore.ServiceDefaults.ANcpLuaServiceDefaultsOptions>();");
            sb.AppendLine("            return builder.Build();");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("ANcpLua.ServiceDefaults.AutoRegister.g.cs", sb.ToString());
    }

    private static string EscapeForCSharpString(string value)
    {
        return value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal);
    }

    private readonly record struct InterceptLocation(string FilePath, int Line, int Column);
}
