// <auto-generated>
// Polyfill for string extension methods not available in netstandard2.0
// Satisfies CA1307/CA2249 analyzer rules
// </auto-generated>

#if NETSTANDARD2_0 || NETSTANDARD2_1

using System.Text;

namespace System;

/// <summary>
/// Extension methods for <see cref="string"/> that provide overloads with <see cref="StringComparison"/>.
/// These APIs exist natively in .NET 5+ but are missing in netstandard2.0.
/// </summary>
internal static class StringExtensionsPolyfill
{
    /// <summary>
    /// Returns a value indicating whether a specified character occurs within this string.
    /// </summary>
    /// <param name="str">The string to search.</param>
    /// <param name="value">The character to seek.</param>
    /// <returns>true if the value parameter occurs within this string; otherwise, false.</returns>
    public static bool Contains(this string str, char value)
        => str.IndexOf(value) >= 0;

    /// <summary>
    /// Returns a value indicating whether a specified string occurs within this string,
    /// using the specified comparison rules.
    /// </summary>
    /// <param name="str">The string to search.</param>
    /// <param name="value">The string to seek.</param>
    /// <param name="comparisonType">One of the enumeration values that specifies the rules for the search.</param>
    /// <returns>true if the value parameter occurs within this string; otherwise, false.</returns>
    public static bool Contains(this string str, string value, StringComparison comparisonType)
        => str.IndexOf(value, comparisonType) >= 0;

    /// <summary>
    /// Returns a value indicating whether a specified character occurs within this string,
    /// using the specified comparison rules.
    /// </summary>
    /// <param name="str">The string to search.</param>
    /// <param name="value">The character to seek.</param>
    /// <param name="comparisonType">One of the enumeration values that specifies the rules for the search.</param>
    /// <returns>true if the value parameter occurs within this string; otherwise, false.</returns>
    public static bool Contains(this string str, char value, StringComparison comparisonType)
        => str.IndexOf(value.ToString(), comparisonType) >= 0;

    /// <summary>
    /// Returns a new string in which all occurrences of a specified string in the current instance
    /// are replaced with another specified string, using the specified comparison type.
    /// </summary>
    /// <param name="str">The string to search.</param>
    /// <param name="oldValue">The string to be replaced.</param>
    /// <param name="newValue">The string to replace all occurrences of oldValue.</param>
    /// <param name="comparisonType">One of the enumeration values that specifies the rules for the search.</param>
    /// <returns>A string with all occurrences of oldValue replaced by newValue.</returns>
    public static string Replace(this string str, string oldValue, string? newValue, StringComparison comparisonType)
    {
        if (oldValue is null)
            throw new ArgumentNullException(nameof(oldValue));
        if (oldValue.Length == 0)
            throw new ArgumentException("String cannot be empty.", nameof(oldValue));

        var sb = new StringBuilder();
        var previousIndex = 0;
        int index;

        while ((index = str.IndexOf(oldValue, previousIndex, comparisonType)) >= 0)
        {
            sb.Append(str, previousIndex, index - previousIndex);
            sb.Append(newValue ?? string.Empty);
            previousIndex = index + oldValue.Length;
        }

        sb.Append(str, previousIndex, str.Length - previousIndex);
        return sb.ToString();
    }

    /// <summary>
    /// Splits a string into substrings based on a specified delimiting character.
    /// </summary>
    /// <param name="str">The string to split.</param>
    /// <param name="separator">A character that delimits the substrings.</param>
    /// <param name="options">A bitwise combination of the enumeration values that specifies whether to trim substrings and include empty substrings.</param>
    /// <returns>An array whose elements contain the substrings from this instance.</returns>
    public static string[] Split(this string str, char separator, StringSplitOptions options = StringSplitOptions.None)
        => str.Split(new[] { separator }, options);

    /// <summary>
    /// Splits a string into substrings based on a specified delimiting string.
    /// </summary>
    /// <param name="str">The string to split.</param>
    /// <param name="separator">A string that delimits the substrings.</param>
    /// <param name="options">A bitwise combination of the enumeration values that specifies whether to trim substrings and include empty substrings.</param>
    /// <returns>An array whose elements contain the substrings from this instance.</returns>
    public static string[] Split(this string str, string? separator, StringSplitOptions options = StringSplitOptions.None)
        => str.Split(separator is null ? null : new[] { separator }, options);
}

#endif
