// <auto-generated>
// This file is auto-generated by ANcpLua.NET.Sdk.
// Do not modify - changes will be overwritten.
// </auto-generated>

#nullable enable

using Basic.Reference.Assemblies;
using Microsoft.CodeAnalysis.CodeFixes;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Testing;

namespace ANcpLua.Testing.Analyzers;

/// <summary>
/// Base class for code fix unit tests.
/// Provides pre-configured reference assemblies for .NET 10.
/// </summary>
/// <typeparam name="TAnalyzer">The analyzer type that produces the diagnostics.</typeparam>
/// <typeparam name="TCodeFix">The code fix provider to test.</typeparam>
public abstract class CodeFixTest<TAnalyzer, TCodeFix>
    where TAnalyzer : DiagnosticAnalyzer, new()
    where TCodeFix : CodeFixProvider, new() {
    private static readonly ReferenceAssemblies Net100Tfm = new("net10.0");

    /// <summary>
    /// Verifies that the code fix transforms the source as expected.
    /// </summary>
    /// <param name="source">The source code with diagnostic markers.</param>
    /// <param name="fixedSource">The expected source after the fix is applied.</param>
    protected static Task VerifyAsync(string source, string fixedSource) {
        var test = new CSharpCodeFixTest<TAnalyzer, TCodeFix, DefaultVerifier> {
            TestCode = source.ReplaceLineEndings(),
            FixedCode = fixedSource.ReplaceLineEndings(),
            ReferenceAssemblies = Net100Tfm
        };

        test.TestState.AdditionalReferences.AddRange(Net100.References.All);

        return test.RunAsync();
    }
}
