// <auto-generated by ANcpLua.NET.Sdk />
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Diagnostics.Testing;

namespace ANcpLua.Testing;

public static class FakeLoggerExtensions
{
    public static string GetFullLoggerText(
        this FakeLogCollector source,
        Func<FakeLogRecord, string>? formatter = null)
    {
        var sb = new StringBuilder();
        formatter ??= record => $"{record.Level} - {record.Message}";
        foreach (var record in source.GetSnapshot())
            sb.AppendLine(formatter(record));
        return sb.ToString();
    }

    public static async Task<bool> WaitForLogAsync(
        this FakeLogCollector source,
        Func<IReadOnlyList<FakeLogRecord>, bool> condition,
        TimeSpan? timeout = null,
        CancellationToken ct = default)
    {
        timeout ??= TimeSpan.FromSeconds(5);
        using var cts = CancellationTokenSource.CreateLinkedTokenSource(ct);
        cts.CancelAfter(timeout.Value);

        try
        {
            while (!cts.Token.IsCancellationRequested)
            {
                if (condition(source.GetSnapshot())) return true;
                await Task.Delay(25, cts.Token);
            }
        }
        catch (OperationCanceledException) when (!ct.IsCancellationRequested) { }

        return condition(source.GetSnapshot());
    }

    public static Task<bool> WaitForLogCountAsync(
        this FakeLogCollector source,
        Func<FakeLogRecord, bool> predicate,
        int expectedCount,
        TimeSpan? timeout = null,
        CancellationToken ct = default)
    {
        return source.WaitForLogAsync(
            logs => logs.Count(predicate) >= expectedCount,
            timeout,
            ct);
    }
}
