// <auto-generated by ANcpLua.NET.Sdk />
#nullable enable
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.TestHost;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Testing;
using Xunit;

namespace ANcpLua.Testing;

/// <summary>
/// Fast integration test base using in-memory TestServer.
/// Use for most API tests. SDK auto-injects this.
/// </summary>
public abstract class IntegrationTestBase<TProgram> : IClassFixture<WebApplicationFactory<TProgram>>, IAsyncLifetime
    where TProgram : class
{
    private WebApplicationFactory<TProgram>? _factory;
    
    protected WebApplicationFactory<TProgram> Factory => _factory!;
    protected HttpClient Client { get; private set; } = null!;
    protected FakeLogCollector Logs { get; } = new();

    protected IntegrationTestBase(WebApplicationFactory<TProgram> factory)
    {
        _factory = factory.WithWebHostBuilder(builder =>
        {
            builder.ConfigureTestServices(ConfigureTestServices);
        });
    }

    protected virtual void ConfigureTestServices(IServiceCollection services)
    {
        services.AddFakeLogging(options => options.OutputSink = Logs);
    }

    public virtual Task InitializeAsync()
    {
        Client = Factory.CreateClient();
        return Task.CompletedTask;
    }

    public virtual Task DisposeAsync()
    {
        Client?.Dispose();
        return Task.CompletedTask;
    }
}
