// <auto-generated by ANcpLua.NET.Sdk />
#nullable enable
using System;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.TestHost;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Diagnostics.Testing;
using Xunit;

namespace ANcpLua.Testing;

/// <summary>
/// Real Kestrel test base for HTTP/2, WebSockets, SSE, Playwright.
/// SDK auto-injects this. Uses UseKestrel(0) + StartServer().
/// </summary>
public abstract class KestrelTestBase<TProgram> : IAsyncLifetime
    where TProgram : class
{
    private readonly WebApplicationFactory<TProgram> _baseFactory;
    private WebApplicationFactory<TProgram>? _startedFactory;

    protected HttpClient Client { get; private set; } = null!;
    protected FakeLogCollector Logs { get; } = new();
    protected Uri BaseAddress => _startedFactory?.ClientOptions.BaseAddress
        ?? throw new InvalidOperationException("Server not started");

    protected KestrelTestBase(WebApplicationFactory<TProgram> factory)
    {
        _baseFactory = factory.WithWebHostBuilder(builder =>
        {
            builder.ConfigureTestServices(ConfigureTestServices);
        });
    }

    protected virtual void ConfigureTestServices(IServiceCollection services)
    {
        services.AddFakeLogging(options => options.OutputSink = Logs);
    }

    public virtual ValueTask InitializeAsync()
    {
        _startedFactory = _baseFactory.UseKestrel(0);
        _startedFactory.StartServer();
        Client = _startedFactory.CreateClient(new WebApplicationFactoryClientOptions
        {
            AllowAutoRedirect = false
        });
        return ValueTask.CompletedTask;
    }

    public virtual async ValueTask DisposeAsync()
    {
        Client?.Dispose();
        if (_startedFactory is not null)
            await _startedFactory.DisposeAsync();
    }
}
