// <auto-generated />
#nullable enable

namespace ANcpLua.Analyzers;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

/// <summary>
/// Extension methods for working with syntax modifiers.
/// </summary>
internal static class SyntaxModifierExtensions
{
    /// <summary>
    /// Ensures a modifier exists in the token list, inserting it if missing.
    /// </summary>
    public static SyntaxTokenList EnsureModifier(
        this SyntaxTokenList modifiers,
        SyntaxKind kind,
        ModifierPosition position = ModifierPosition.AfterAccessibility)
    {
        if (modifiers.Any(kind)) return modifiers;

        var insertIndex = position switch
        {
            ModifierPosition.Start => 0,
            ModifierPosition.AfterAccessibility => GetAccessibilityEndIndex(modifiers),
            ModifierPosition.BeforePartial => GetPartialIndex(modifiers),
            ModifierPosition.End => modifiers.Count,
            _ => modifiers.Count
        };

        return modifiers.Insert(insertIndex, SyntaxFactory.Token(kind).WithTrailingTrivia(SyntaxFactory.Space));
    }

    /// <summary>
    /// Removes a modifier from the token list if present.
    /// </summary>
    public static SyntaxTokenList RemoveModifier(this SyntaxTokenList modifiers, SyntaxKind kind)
    {
        var index = modifiers.IndexOf(kind);
        return index >= 0 ? modifiers.RemoveAt(index) : modifiers;
    }

    private static int GetAccessibilityEndIndex(SyntaxTokenList modifiers)
    {
        for (var i = 0; i < modifiers.Count; i++)
        {
            if (!IsAccessibilityModifier(modifiers[i].Kind()))
                return i;
        }
        return modifiers.Count;
    }

    private static int GetPartialIndex(SyntaxTokenList modifiers)
    {
        var index = modifiers.IndexOf(SyntaxKind.PartialKeyword);
        return index >= 0 ? index : modifiers.Count;
    }

    private static bool IsAccessibilityModifier(SyntaxKind kind) =>
        kind is SyntaxKind.PublicKeyword or SyntaxKind.PrivateKeyword or
               SyntaxKind.ProtectedKeyword or SyntaxKind.InternalKeyword;
}

/// <summary>
/// Where to insert a modifier in the token list.
/// </summary>
internal enum ModifierPosition
{
    Start,
    AfterAccessibility,
    BeforePartial,
    End
}
